export const versionColors: Record<string, { border: string; text: string; hoverBg: string; bg: string }> = {
  red: { border: 'border-red-500', text: 'text-red-500', hoverBg: 'hover:bg-red-50', bg: 'bg-red-500' },
  blue: { border: 'border-blue-500', text: 'text-blue-500', hoverBg: 'hover:bg-blue-50', bg: 'bg-blue-500' },
  yellow: { border: 'border-yellow-500', text: 'text-yellow-600', hoverBg: 'hover:bg-yellow-50', bg: 'bg-yellow-400' },
  gold: { border: 'border-yellow-600', text: 'text-yellow-600', hoverBg: 'hover:bg-yellow-50', bg: 'bg-yellow-600' },
  silver: { border: 'border-gray-400', text: 'text-gray-500', hoverBg: 'hover:bg-gray-50', bg: 'bg-gray-400' },
  crystal: { border: 'border-cyan-400', text: 'text-cyan-500', hoverBg: 'hover:bg-cyan-50', bg: 'bg-cyan-400' },
  ruby: { border: 'border-red-700', text: 'text-red-700', hoverBg: 'hover:bg-red-50', bg: 'bg-red-700' },
  sapphire: { border: 'border-blue-700', text: 'text-blue-700', hoverBg: 'hover:bg-blue-50', bg: 'bg-blue-700' },
  emerald: { border: 'border-emerald-500', text: 'text-emerald-500', hoverBg: 'hover:bg-emerald-50', bg: 'bg-emerald-500' },
  firered: { border: 'border-orange-500', text: 'text-orange-500', hoverBg: 'hover:bg-orange-50', bg: 'bg-orange-500' },
  leafgreen: { border: 'border-green-500', text: 'text-green-500', hoverBg: 'hover:bg-green-50', bg: 'bg-green-500' },
  diamond: { border: 'border-cyan-300', text: 'text-cyan-400', hoverBg: 'hover:bg-cyan-50', bg: 'bg-cyan-300' },
  pearl: { border: 'border-pink-300', text: 'text-pink-400', hoverBg: 'hover:bg-pink-50', bg: 'bg-pink-300' },
  platinum: { border: 'border-gray-500', text: 'text-gray-500', hoverBg: 'hover:bg-gray-50', bg: 'bg-gray-500' },
  heartgold: { border: 'border-yellow-500', text: 'text-yellow-500', hoverBg: 'hover:bg-yellow-50', bg: 'bg-yellow-500' },
  soulsilver: { border: 'border-slate-400', text: 'text-slate-400', hoverBg: 'hover:bg-slate-50', bg: 'bg-slate-400' },
  black: { border: 'border-gray-900', text: 'text-gray-900', hoverBg: 'hover:bg-gray-50', bg: 'bg-gray-900' },
  white: { border: 'border-gray-300', text: 'text-gray-400', hoverBg: 'hover:bg-gray-50', bg: 'bg-gray-200' },
  'black-2': { border: 'border-gray-800', text: 'text-gray-800', hoverBg: 'hover:bg-gray-50', bg: 'bg-gray-800' },
  'white-2': { border: 'border-gray-300', text: 'text-gray-400', hoverBg: 'hover:bg-gray-50', bg: 'bg-gray-200' },
  x: { border: 'border-blue-600', text: 'text-blue-600', hoverBg: 'hover:bg-blue-50', bg: 'bg-blue-600' },
  y: { border: 'border-red-600', text: 'text-red-600', hoverBg: 'hover:bg-red-50', bg: 'bg-red-600' },
  'omega-ruby': { border: 'border-red-700', text: 'text-red-700', hoverBg: 'hover:bg-red-50', bg: 'bg-red-700' },
  'alpha-sapphire': { border: 'border-blue-700', text: 'text-blue-700', hoverBg: 'hover:bg-blue-50', bg: 'bg-blue-700' },
  sun: { border: 'border-orange-400', text: 'text-orange-400', hoverBg: 'hover:bg-orange-50', bg: 'bg-orange-400' },
  moon: { border: 'border-purple-600', text: 'text-purple-600', hoverBg: 'hover:bg-purple-50', bg: 'bg-purple-600' },
  'ultra-sun': { border: 'border-orange-500', text: 'text-orange-500', hoverBg: 'hover:bg-orange-50', bg: 'bg-orange-500' },
  'ultra-moon': { border: 'border-purple-700', text: 'text-purple-700', hoverBg: 'hover:bg-purple-50', bg: 'bg-purple-700' },
  'lets-go-pikachu': { border: 'border-yellow-400', text: 'text-yellow-500', hoverBg: 'hover:bg-yellow-50', bg: 'bg-yellow-400' },
  'lets-go-eevee': { border: 'border-amber-600', text: 'text-amber-600', hoverBg: 'hover:bg-amber-50', bg: 'bg-amber-600' },
  sword: { border: 'border-cyan-500', text: 'text-cyan-500', hoverBg: 'hover:bg-cyan-50', bg: 'bg-cyan-500' },
  shield: { border: 'border-red-500', text: 'text-red-500', hoverBg: 'hover:bg-red-50', bg: 'bg-red-500' },
  'brilliant-diamond': { border: 'border-cyan-400', text: 'text-cyan-400', hoverBg: 'hover:bg-cyan-50', bg: 'bg-cyan-400' },
  'shining-pearl': { border: 'border-pink-400', text: 'text-pink-400', hoverBg: 'hover:bg-pink-50', bg: 'bg-pink-400' },
  'legends-arceus': { border: 'border-indigo-600', text: 'text-indigo-600', hoverBg: 'hover:bg-indigo-50', bg: 'bg-indigo-600' },
  scarlet: { border: 'border-red-600', text: 'text-red-600', hoverBg: 'hover:bg-red-50', bg: 'bg-red-600' },
  violet: { border: 'border-violet-600', text: 'text-violet-600', hoverBg: 'hover:bg-violet-50', bg: 'bg-violet-600' },
};

export const getVersionColor = (version: string) => {
  return versionColors[version] || { border: 'border-gray-400', text: 'text-gray-500', hoverBg: 'hover:bg-gray-50', bg: 'bg-gray-400' };
};